In [2]:
import pickle
import pandas as pd
import numpy as np

In [3]:
ohe_emb = pickle.load(open('/Users/shishir/100 days of ML/Feature Engineering/sklearn-pipelines/models/ohe_emb.pkl', 'rb'))
ohe_sex = pickle.load(open('/Users/shishir/100 days of ML/Feature Engineering/sklearn-pipelines/models/ohe_sex.pkl', 'rb'))
clf = pickle.load(open('/Users/shishir/100 days of ML/Feature Engineering/sklearn-pipelines/models/clf.pkl', 'rb'))

In [4]:
arr = np.array([2,'male',31.0, 0, 0, 10.5, 'S'])
arr, arr.shape
# by default everything is stored as string. If we want to retain original datatype, use dtype = 'object'
# (7,) represents 1D array
# reshape(1,7) makes it 2-Dimensional [[2,'male',31.0, 0, 0, 10.5, 'S']]

(array(['2', 'male', '31.0', '0', '0', '10.5', 'S'], dtype='<U32'), (7,))

In [7]:
test_input = np.array([2,'male',31.0, 0, 0, 10.5, 'S'], dtype='object').reshape(1,7) # numpy.ndarray
test_input, test_input.shape # 1 row, 7 columns

(array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object), (1, 7))

In [8]:
# Now we need to apply same preprocessing steps that we applied at the time of training

In [14]:
test_input[:,1], type(test_input[:,1]) # numpy 1D array

(array(['male'], dtype=object), numpy.ndarray)

In [16]:
test_input[:,1].reshape(1,1) # 2D dataframe (1 row, 1 col)

array([['male']], dtype=object)

In [17]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))
test_input_sex

/Users/shishir/anaconda3/envs/my-env/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0.]])

In [18]:
test_input_emb = ohe_emb.transform(test_input[:,-1].reshape(1,1))
test_input_emb

array([[0., 0., 1.]])

In [24]:
test_input_age = test_input[:,2].reshape(1,1)
test_input_age

array([[31.0]], dtype=object)

In [25]:
# maintaining order is very crucial
# remaining cols, age, sex, embarked
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]], test_input_age, test_input_sex, test_input_emb), axis=1)
test_input_transformed, test_input_transformed.shape

(array([[2, 0, 0, 10.5, 31.0, 1.0, 0.0, 0.0, 0.0, 1.0]], dtype=object),
 (1, 10))

In [26]:
clf.predict(test_input_transformed)

array([0])

In [ ]:
## If you can see -- there are a lot of vulnerabilities and duplicate work happening here. 
## We have to repeat the exact same steps that we followed while training the model, in order to predict new vales
## even a slight change in the training set, we will have to replicate the same in the prediction step as well
## Error Prone, Duplicated code, same series of steps followed in the production code

## Better way to handle this is to use pipeline