In [14]:
import numpy as np
import pandas as pd

In [15]:
df = pd.read_csv('titanic/train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


## dropping rows/cols from pd dataframe

In [16]:
# either specify columns list -- pandas will drop the cols automatically
df = df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'])
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,0,3,male,22.0,1,0,7.2500,S
1,1,1,female,38.0,1,0,71.2833,C
2,1,3,female,26.0,0,0,7.9250,S
3,1,1,female,35.0,1,0,53.1000,S
4,0,3,male,35.0,0,0,8.0500,S


In [9]:
# or if you just specify the list, then you need to tell the axis. axis=1 is for col and axis=0 is for rows
# by default axis=0
df2 = df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

In [12]:
df2.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,0,3,male,22.0,1,0,7.2500,S
1,1,1,female,38.0,1,0,71.2833,C
2,1,3,female,26.0,0,0,7.9250,S
3,1,1,female,35.0,1,0,53.1000,S
4,0,3,male,35.0,0,0,8.0500,S


In [13]:
# this will drop the 0th and 1st row, by default axis = 0
df2.drop([0,1])

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
2,1,3,female,26.0,0,0,7.9250,S
3,1,1,female,35.0,1,0,53.1000,S
4,0,3,male,35.0,0,0,8.0500,S
5,0,3,male,NaN,0,0,8.4583,Q
6,0,1,male,54.0,0,0,51.8625,S
...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S
887,1,1,female,19.0,0,0,30.0000,S
888,0,3,female,NaN,1,2,23.4500,S
889,1,1,male,26.0,0,0,30.0000,C


In [17]:
df.shape

(891, 8)

## checking nulls 

In [22]:
df.isnull().sum()
# will have to fill the null values in age and embarked
# will use mean to replace the missing age
# will use the most_frequent value to replace the missing Embarked values

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [23]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [33]:
# df['Embarked'].unique()

# this wont work because np.nan == np.nan returns False
# for NaN using == or != fails
# use isnull() or isna()

# df[df['Embarked']==nan] X Wrong

df[df['Embarked'].isnull()]

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
61,1,1,female,38.0,0,0,80.0,NaN
829,1,1,female,62.0,0,0,80.0,NaN


In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    df.iloc[:,1:],
    df.iloc[:,0],
    test_size=0.2,
    random_state=42
)

In [21]:
X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
331,1,male,45.5,0,0,28.5000,S
733,2,male,23.0,0,0,13.0000,S
382,3,male,32.0,0,0,7.9250,S
704,3,male,26.0,1,0,7.8542,S
813,3,female,6.0,4,2,31.2750,S
...,...,...,...,...,...,...,...
106,3,female,21.0,0,0,7.6500,S
270,1,male,NaN,0,0,31.0000,S
860,3,male,41.0,2,0,14.1083,S
435,1,female,14.0,1,2,120.0000,S


In [116]:
y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64

## Impute Missing Values

In [35]:
from sklearn.impute import SimpleImputer

In [36]:
age_imp = SimpleImputer()
emb_imp = SimpleImputer(strategy='most_frequent')

In [96]:
X_train_age_imp = age_imp.fit_transform(X_train[['Age']])
X_test_age_imp = age_imp.transform(X_test[['Age']])

X_train_age_imp.shape

(712, 1)

In [95]:
X_train_emb_imp =  emb_imp.fit_transform(X_train[['Embarked']])
X_test_emb_imp = emb_imp.transform(X_test[['Embarked']])

X_train_emb_imp # ndarray

array([['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
      

## pd dataframe vs series quick cmp

In [50]:
X_train[['Embarked']].shape # [[]] gives you dataframe

(712, 1)

In [51]:
X_train['Embarked'].shape # [] gives you series

(712,)

In [56]:
X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
331,1,male,45.5,0,0,28.5000,S
733,2,male,23.0,0,0,13.0000,S
382,3,male,32.0,0,0,7.9250,S
704,3,male,26.0,1,0,7.8542,S
813,3,female,6.0,4,2,31.2750,S
...,...,...,...,...,...,...,...
106,3,female,21.0,0,0,7.6500,S
270,1,male,NaN,0,0,31.0000,S
860,3,male,41.0,2,0,14.1083,S
435,1,female,14.0,1,2,120.0000,S


## One hot encoding on nominal categorical variables

In [54]:
from sklearn.preprocessing import OneHotEncoder

In [79]:
# creating a test encoder object to verify its behaviour with categories parameter
ohe_sex_tmp = OneHotEncoder(sparse_output=False)
ohe_sex_tmp.fit(X_train[['Sex']])

# Notice that sklearn sorts categories alphabetically by default.
print(ohe_sex_tmp.categories_)

[array(['female', 'male'], dtype=object)]


In [85]:
# No, it's not mandatory to pass categories.
# without categories: During fit(), sklearn automatically discovers the categories from the training data
# by default: sklearn sorts categories alphabetically by default.
# when we pass categories explicitly, we're explicitly telling sklearn 

# when would you specify categories:
# 1. you need consistent col ordering
    # without categories
    #     OneHotEncoder(sparse_output=False)
    # will produce 
    #     female  male
    #     1       0
    #     0       1
# because sklearn sorted them alphabetically.
    # With:
    #     categories=[['male','female']]
    # you get:
    # male  female
    # 1     0
    # 0     1

# 2. handle missing categories in training data.
# Suppose your training set accidentally contains only: male
# Without specifying categories:
#     ohe.fit(X_train)
# sklearn learns only:
# ['male']
# and creates just one encoded column.
# Later, when test data contains "female", you'll run into issues (unless using appropriate handle_unknown settings).
# By specifying:
#     categories=[['male','female']]

# you ensure both columns always exist.

# 3. Control drop = 'first'
# The category that gets dropped depends on the category ordering.
# categories=[['male','female']]
# male -> dropped
# female -> encoded column


# best practise: always specify categories: things are more clear
ohe_sex = OneHotEncoder(categories=[['male','female']], sparse_output=False)

In [92]:
X_train_sex_ohe = ohe_sex.fit_transform(X_train[['Sex']])
X_test_sex_ohe = ohe_sex.transform(X_test[['Sex']])

X_train_sex_ohe.shape

(712, 2)

In [87]:
ohe_sex.categories_

[array(['male', 'female'], dtype=object)]

In [88]:
ohe_emb = OneHotEncoder(sparse_output=False)

In [89]:
X_train_emb_ohe = ohe_emb.fit_transform(X_train_emb_imp)
X_test_emb_ohe = ohe_emb.transform(X_test_emb_imp)

In [90]:
X_train_emb_ohe

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], shape=(712, 3))

In [91]:
type(X_train_emb_ohe)

numpy.ndarray

## concatenate all the transformed cols together

In [106]:
X_train_sex_ohe # 2 col
X_train_emb_ohe # 3 col
X_train_age_imp # 1 col

array([[45.5       ],
       [23.        ],
       [32.        ],
       [26.        ],
       [ 6.        ],
       [24.        ],
       [45.        ],
       [29.        ],
       [29.49884615],
       [29.49884615],
       [42.        ],
       [36.        ],
       [33.        ],
       [17.        ],
       [29.        ],
       [50.        ],
       [35.        ],
       [38.        ],
       [34.        ],
       [17.        ],
       [11.        ],
       [61.        ],
       [30.        ],
       [ 7.        ],
       [63.        ],
       [20.        ],
       [29.49884615],
       [29.        ],
       [36.        ],
       [29.49884615],
       [50.        ],
       [27.        ],
       [30.        ],
       [33.        ],
       [29.49884615],
       [29.49884615],
       [ 2.        ],
       [25.        ],
       [51.        ],
       [25.        ],
       [29.49884615],
       [29.49884615],
       [24.        ],
       [18.        ],
       [29.49884615],
       [25

In [97]:
X_train.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
331,1,male,45.5,0,0,28.5000,S
733,2,male,23.0,0,0,13.0000,S
382,3,male,32.0,0,0,7.9250,S
704,3,male,26.0,1,0,7.8542,S
813,3,female,6.0,4,2,31.2750,S


In [108]:
X_train_remaining = X_train.drop(columns=['Sex', 'Embarked', 'Age'])
X_test_remaining = X_test.drop(columns=['Sex', 'Embarked', 'Age'])

X_train_remaining.head()

,Pclass,SibSp,Parch,Fare
331,1,0,0,28.5000
733,2,0,0,13.0000
382,3,0,0,7.9250
704,3,1,0,7.8542
813,3,4,2,31.2750


In [103]:
X_train_remaining.values

array([[  1.    ,   0.    ,   0.    ,  28.5   ],
       [  2.    ,   0.    ,   0.    ,  13.    ],
       [  3.    ,   0.    ,   0.    ,   7.925 ],
       ...,
       [  3.    ,   2.    ,   0.    ,  14.1083],
       [  1.    ,   1.    ,   2.    , 120.    ],
       [  1.    ,   0.    ,   1.    ,  77.2875]], shape=(712, 4))

In [111]:
# now merge all of them
# X_train_remaining --> pandas dataframe
# To convert the df into ndarray --> X_train_remaining.values

X_train_transformed = np.concatenate((X_train_remaining.values, X_train_age_imp, X_train_sex_ohe, X_train_emb_ohe), axis=1)
X_test_transformed = np.concatenate((X_test_remaining.values, X_test_age_imp, X_test_sex_ohe, X_test_emb_ohe), axis=1)

X_train_transformed.shape, X_test_transformed.shape 

((712, 10), (179, 10))

## model training

In [112]:
from sklearn.tree import DecisionTreeClassifier

In [113]:
clf =DecisionTreeClassifier()

In [118]:
# model training
clf.fit(X_train_transformed, y_train)

,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.",'gini'
,"splitter splitter: {""best"", ""random""}, default=""best""The strategy used to choose the split at each node. Supportedstrategies are ""best"" to choose the best split and ""random"" to choosethe best random split.",'best'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: int, float or {""sqrt"", ""log2""}, default=NoneThe number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... note:: The search for a split does not stop until at least one valid partition of the node samples is found, even if it requires to effectively inspect more than ``max_features`` features.",None
,"random_state random_state: int, RandomState instance or None, default=NoneControls the randomness of the estimator. The features are alwaysrandomly permuted at each split, even if ``splitter`` is set to``""best""``. When ``max_features < n_features``, the algorithm willselect ``max_features`` at random at each split before finding the bestsplit among them. But the best found split may vary across differentruns, even if ``max_features=n_features``. That is the case, if theimprovement of the criterion is identical for several splits and onesplit has to be selected at random. To obtain a deterministic behaviourduring fitting, ``random_state`` has to be fixed to an integer.See :term:`Glossary ` for details.",None
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow a tree with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the curre

In [148]:
y_pred = clf.predict(X_test_transformed)
y_pred

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1])

In [121]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7988826815642458

In [124]:
y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64

## Exporting the model and the encoders

In [149]:
import pickle

In [154]:
import os
os.getcwd()

print(os.path.exists('/Users/shishir/100 days of ML/Feature Engineering/sklearn-pipelines/models/'))

True


In [155]:
# I need to export the classifier model and the encoders. 
# Plan is there will be website from where I'll take the input from the users and then make the prediction whether the person will survive or not
# not exporting age imputer here, coz user will anyway provide the age in the form.

pickle.dump(ohe_emb, open('/Users/shishir/100 days of ML/Feature Engineering/sklearn-pipelines/models/ohe_emb.pkl', 'wb'))
pickle.dump(ohe_sex, open('/Users/shishir/100 days of ML/Feature Engineering/sklearn-pipelines/models/ohe_sex.pkl', 'wb'))
pickle.dump(clf, open('/Users/shishir/100 days of ML/Feature Engineering/sklearn-pipelines/models/clf.pkl', 'wb'))

## loading the pickle objects back

In [157]:
ohe_emb = pickle.load(open('/Users/shishir/100 days of ML/Feature Engineering/sklearn-pipelines/models/ohe_emb.pkl', 'rb'))
ohe_sex = pickle.load(open('/Users/shishir/100 days of ML/Feature Engineering/sklearn-pipelines/models/ohe_sex.pkl', 'rb'))
clf = pickle.load(open('/Users/shishir/100 days of ML/Feature Engineering/sklearn-pipelines/models/clf.pkl', 'rb'))

In [160]:
## assume the user input
## Pclass/gender/age/SibSp/Parch/Fare/Embarked

# dtype='object' tells NumPy - Don't force everything into a single numeric/string type. Store each value as its original Python object.
test_input = np.array([2,'male',31.0, 0, 0, 10.5, 'S'], dtype='object').reshape(1,7)
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [ ]:
# Reason why prefer using pipelines
# without pipelines
# code was getting duplicated -- the code which we writ


## pandas series vs numpy ndarray

In [129]:
arr = np.array([10,20,30])
arr

array([10, 20, 30])

In [130]:
arr[0]

np.int64(10)

### pandas series

In [131]:
s = pd.Series([10,20,30])
s

0    10
1    20
2    30
dtype: int64

In [132]:
# notice the index: 0,1,2
# we can even define our own
s = pd.Series([10,20,30], index=['a','b','c'])
s

a    10
b    20
c    30
dtype: int64

In [133]:
# now you can do 
s['a']
# this is impossible with a plain ndarray

np.int64(10)

In [136]:
# A Series is basically
# you can think of Series as 
    # Series = ndarray + Index

# Internally
s.values
# returns the underlying NumPy array
# and 
s.index
# returns the index

Index(['a', 'b', 'c'], dtype='str')

## Alignment Magic

In [137]:
s1 = pd.Series([10,20,30], index=['a','b','c'])
s2 = pd.Series([1,2,3], index=['b','c','d'])

In [139]:
s1.values # gives me ndarray

array([10, 20, 30])

In [140]:
s1.index # gives me index

Index(['a', 'b', 'c'], dtype='str')

In [141]:
# pandas series = ndarray + index

In [143]:
# pandas aligns the values by labels
s1 + s2

a     NaN
b    21.0
c    32.0
d     NaN
dtype: float64

In [147]:
arr1 = np.array([10,20,30])
arr2 = np.array([1,2,3])

arr1+arr2 # to add they should be of the same length 

# NumPy aligns by positions only

array([11, 22, 33])

## Why scikit-learn often returns ndarrays